### ISSUE TITLE
Seems there is a wrong if condition

### ISSUE THREAD

**Issue by lwh19970531** [tobor88/WindowsEventForwarding#3]
https://github.com/OsbornePro/BTPS-SecPack/blob/31f3323e00aafc10584b2da8d81c4c978374b995/Account%20and%20Password%20Alerts/PasswordExpiryAlert.ps1#L54C5-L54C5

**"$ExpirationDate -ge $TodaysDate"** should be "$ExpirationDate -le $TodaysDate" or "$TodaysDate -ge $ExpirationDate"?

**Comment by tobor88** [comment]
It appears you are not looking at the most current branch. Be sure you have "master" selected. I ended up changing that line too (($TodaysDate -ge $ExpirationDate.AddDays(-15)) -and ($TodaysDate -le $ExpirationDate)). Let me know if you come acros anything else
